### ISSUE TITLE
[TODO] Stuff

### ISSUE THREAD

**Issue by SumnDaiy** [SumnDaiy/dolu_hud#1]
- [ ] Create new client file and settings for Informations

- [ ] Better CSS?

- [ ] New placement for UI

- [ ] Possible toggle keybind for it?

**Comment by SumnDaiy** [comment]
wtf was I doing
